# -*- coding: utf-8 -*-
"""game_score.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12D-0HpsYER7hzEfrfY43PYcDFjKfE9wO
"""

player_name = input("Enter the player's name: ")

number_of_games = int(input("Enter the number of games played: "))

total_score = int(input("Enter the total score achieved: "))

average_score = total_score / number_of_games

print(f"\nPlayer: {player_name}")

print(f"Games Played: {number_of_games}")

print(f"Total Score: {total_score}")

print(f"Average Score: {average_score:.2f}")